#include <doctest/doctest.h>
#include <cmath>
#include <random>
#include <vector>
#include <Eigen/Core>
#include "../../src/FlowTracker.h"
#include "../../src/GaussianInfo.hpp"
#include "../../src/MeasurementFlowRotation.h"
#include "../../src/Pose.hpp"
#include "../../src/rotation.hpp"
#include "../../src/SystemLocalisation.h"
#include "stateHelpers.hpp"

#ifndef M_PI
#define M_PI 3.14159265358979323846264338327950288
#endif

namespace
{

/// @brief A spread of unit rays over the forward hemisphere, deterministic across runs.
std::vector<Eigen::Vector3d> fanOfRays(int n)
{
    std::vector<Eigen::Vector3d> rays;
    rays.reserve(static_cast<std::size_t>(n));
    for (int i = 0; i < n; ++i)
    {
        // Fibonacci-ish spiral over a cap, so the rays span a real solid angle
        // rather than lining up (a degenerate spread cannot observe all three
        // rotation components, which is the point of spreading them).
        const double a = 2.39996*i;
        const double r = 0.9*std::sqrt(static_cast<double>(i)/n);
        rays.push_back(Eigen::Vector3d(r*std::cos(a), r*std::sin(a), 1.0).normalized());
    }
    return rays;
}

/**
 * @brief A synthetic FlowFrame generated by rotating a fan of rays at a known body rate.
 *
 * The camera is offset from the torso by a fixed rotation, and the head may move
 * between the two frames, so the test exercises the kinematic term rather than
 * assuming Rbc is the identity.
 */
FlowFrame makeFlowFrame(const Eigen::Vector3d & omega, double dt,
                        const Eigen::Matrix3d & RbcPrev, const Eigen::Matrix3d & RbcCurr,
                        int n = 120, double noiseSigma = 0.0)
{
    FlowFrame ff;
    ff.valid = true;
    ff.dt = dt;
    ff.RbcPrev = RbcPrev;
    ff.RbcCurr = RbcCurr;

    const Eigen::Matrix3d Rck_ckm1 = RbcCurr.transpose()*expSO3(Eigen::Vector3d(-dt*omega))*RbcPrev;

    std::mt19937 gen(12345);
    std::normal_distribution<double> noise(0.0, noiseSigma);

    for (const Eigen::Vector3d & u : fanOfRays(n))
    {
        FlowMatch m;
        m.uPrev = u;
        m.uCurr = Rck_ckm1*u;
        if (noiseSigma > 0.0)
        {
            m.uCurr += Eigen::Vector3d(noise(gen), noise(gen), noise(gen));
            m.uCurr.normalize();
        }
        m.pxPrev = Eigen::Vector2d::Zero();
        m.pxCurr = Eigen::Vector2d::Zero();
        ff.matches.push_back(m);
    }
    ff.nTracked = n;
    return ff;
}

/// @brief A prior centred on a state, loose enough not to fight the measurement.
SystemLocalisation systemAt(const Eigen::VectorXd & x, double sigma = 0.5)
{
    auto p0 = GaussianInfo<double>::fromSqrtMoment(
        x, Eigen::MatrixXd(Eigen::MatrixXd::Identity(SystemLocalisation::nx, SystemLocalisation::nx)*sigma));
    return SystemLocalisation(p0);
}

/// @brief A state carrying a body angular velocity.
Eigen::VectorXd stateWithRate(const Eigen::Vector3d & omega)
{
    Eigen::VectorXd x = makeState(0.0, 0.0, 0.45, 0.0, 0.0, 0.0);
    x.segment<3>(SystemLocalisation::iOmega) = omega;
    return x;
}

}   // namespace

SCENARIO("expSO3 and logSO3 round-trip")
{
    GIVEN("A range of rotation vectors, including the small-angle branch")
    {
        const std::vector<Eigen::Vector3d> ws = {
            Eigen::Vector3d(0.0, 0.0, 0.0),
            Eigen::Vector3d(1e-9, 0.0, 0.0),
            Eigen::Vector3d(1e-5, -2e-5, 3e-5),
            Eigen::Vector3d(0.01, 0.02, -0.03),
            Eigen::Vector3d(0.5, -0.4, 0.3),
            Eigen::Vector3d(2.0, 0.0, 0.0),
        };

        for (const Eigen::Vector3d & w : ws)
        {
            WHEN("Mapping to SO(3) and back")
            {
                const Eigen::Matrix3d R = expSO3(w);

                THEN("the result is a rotation matrix")
                {
                    CHECK((R.transpose()*R - Eigen::Matrix3d::Identity()).norm() == doctest::Approx(0.0).epsilon(1e-12));
                    CHECK(R.determinant() == doctest::Approx(1.0).epsilon(1e-12));
                }

                THEN("logSO3 recovers the rotation vector")
                {
                    CHECK((logSO3(R) - w).norm() == doctest::Approx(0.0).epsilon(1e-9));
                }
            }
        }
    }

    GIVEN("A rotation of pi about an axis")
    {
        // The antisymmetric part of R vanishes here, so the axis has to come out
        // of the symmetric part instead. An inter-frame rotation never reaches
        // this, but a silently wrong axis would be worse than the branch.
        const Eigen::Vector3d w(0.0, 0.0, M_PI);
        const Eigen::Matrix3d R = expSO3(w);

        THEN("logSO3 recovers it up to sign")
        {
            CHECK(std::abs(logSO3(R).z()) == doctest::Approx(M_PI).epsilon(1e-8));
        }
    }
}

SCENARIO("fitRotation recovers a known rotation from ray correspondences")
{
    GIVEN("A fan of rays rotated by a known amount")
    {
        const Eigen::Vector3d w(0.01, -0.02, 0.03);
        const Eigen::Matrix3d R = expSO3(w);

        Eigen::Matrix<double, 3, Eigen::Dynamic> u0(3, 120), u1(3, 120);
        int j = 0;
        for (const Eigen::Vector3d & u : fanOfRays(120))
        {
            u0.col(j) = u;
            u1.col(j) = R*u;
            ++j;
        }

        THEN("the Kabsch fit returns it")
        {
            CHECK((logSO3(fitRotation(u0, u1)) - w).norm() == doctest::Approx(0.0).epsilon(1e-9));
        }
    }
}

SCENARIO("MeasurementFlowRotation recovers the body rate that generated the flow")
{
    const double dt = 1.0/30.0;
    const Eigen::Vector3d omegaTrue(0.05, -0.10, 0.80);   // a brisk turn on the spot

    GIVEN("Flow generated at a known rate, with the head fixed relative to the torso")
    {
        const Eigen::Matrix3d Rbc = rpy2rot(Eigen::Vector3d(0.0, 0.3, 0.0));
        const FlowFrame ff = makeFlowFrame(omegaTrue, dt, Rbc, Rbc);

        const Eigen::VectorXd xTrue = stateWithRate(omegaTrue);
        SystemLocalisation system = systemAt(xTrue);
        MeasurementFlowRotation meas(0.0, ff, system);

        THEN("every match survives the pre-gate")
        {
            CHECK(meas.usable());
            CHECK(meas.numMatches() == ff.matches.size());
            CHECK(meas.numGated() == 0);
        }

        THEN("the robust fit returns the true body rate")
        {
            CHECK((meas.bodyRate() - omegaTrue).norm() == doctest::Approx(0.0).epsilon(1e-6));
        }

        THEN("the log likelihood peaks at the true rate")
        {
            const double llTrue = meas.logLikelihood(xTrue, system);
            Eigen::VectorXd xOff = xTrue;
            xOff(SystemLocalisation::iOmega + 2) += 0.05;
            CHECK(llTrue > meas.logLikelihood(xOff, system));
        }

        THEN("noise-free rays still leave the interval uncertainty behind")
        {
            // The rays are exact here, so everything left is the process model's
            // statement about how much omega can have varied within the frame.
            // This is the term whose omission -- by expressing it as per-ray
            // noise that 190 rays then average away -- made the measurement
            // overconfident enough to drag the run from 0.093 m to 1.28 m.
            MeasurementFlowRotation::Options opts;
            const double expected = std::sqrt(opts.sigmaOmegaPsd*opts.sigmaOmegaPsd*dt*dt*dt/3.0)/dt;
            CHECK(meas.intervalVarianceShare() > 0.99);
            for (int i = 0; i < 3; ++i)
            {
                CHECK(meas.sigma()(i) == doctest::Approx(expected).epsilon(1e-3));
            }
        }
    }

    GIVEN("Flow generated while the head is also panning")
    {
        // The camera turns by the body rate AND the neck. Only the body part is
        // a state; the neck part is known from kinematics and has to cancel.
        const Eigen::Matrix3d RbcPrev = rpy2rot(Eigen::Vector3d(0.0, 0.3, 0.0));
        const Eigen::Matrix3d RbcCurr = rpy2rot(Eigen::Vector3d(0.0, 0.3, 0.02));
        const FlowFrame ff = makeFlowFrame(omegaTrue, dt, RbcPrev, RbcCurr);

        const Eigen::VectorXd xTrue = stateWithRate(omegaTrue);
        SystemLocalisation system = systemAt(xTrue);
        MeasurementFlowRotation meas(0.0, ff, system);

        THEN("the head motion is removed and the body rate still comes back")
        {
            REQUIRE(meas.usable());
            CHECK((meas.bodyRate() - omegaTrue).norm() == doctest::Approx(0.0).epsilon(1e-6));
        }
    }

    GIVEN("Flow while the head is slewing faster than the extrinsic timing can be trusted")
    {
        const Eigen::Matrix3d RbcPrev = rpy2rot(Eigen::Vector3d(0.0, 0.3, 0.0));
        const Eigen::Matrix3d RbcCurr = rpy2rot(Eigen::Vector3d(0.0, 0.3, 0.5));   // 15 rad/s at 30 Hz
        const FlowFrame ff = makeFlowFrame(omegaTrue, dt, RbcPrev, RbcCurr);

        SystemLocalisation system = systemAt(stateWithRate(omegaTrue));
        MeasurementFlowRotation meas(0.0, ff, system);

        THEN("the measurement refuses the frame")
        {
            CHECK_FALSE(meas.usable());
        }
    }
}

SCENARIO("MeasurementFlowRotation derivatives and update")
{
    const double dt = 1.0/30.0;
    const Eigen::Vector3d omegaTrue(0.02, 0.05, -0.40);
    const Eigen::Matrix3d Rbc = rpy2rot(Eigen::Vector3d(0.0, 0.25, 0.0));

    GIVEN("A flow measurement and a state offset from the rate that generated it")
    {
        const FlowFrame ff = makeFlowFrame(omegaTrue, dt, Rbc, Rbc, 120, 0.001);

        Eigen::VectorXd xPrior = stateWithRate(omegaTrue + Eigen::Vector3d(0.05, -0.05, 0.10));
        SystemLocalisation system = systemAt(xPrior);
        MeasurementFlowRotation meas(0.0, ff, system);
        REQUIRE(meas.usable());

        THEN("the gradient matches finite differences")
        {
            Eigen::VectorXd g;
            meas.logLikelihood(xPrior, system, g);
            REQUIRE(g.size() == SystemLocalisation::nx);
            const double h = 1e-7;
            for (int j = 0; j < SystemLocalisation::nx; ++j)
            {
                Eigen::VectorXd xp = xPrior, xm = xPrior;
                xp(j) += h;
                xm(j) -= h;
                const double dfd = (meas.logLikelihood(xp, system) - meas.logLikelihood(xm, system))/(2*h);
                CHECK(g(j) == doctest::Approx(dfd).epsilon(1e-4).scale(1e3));
            }
        }

        THEN("the Hessian matches finite differences of the gradient")
        {
            Eigen::VectorXd g;
            Eigen::MatrixXd H;
            meas.logLikelihood(xPrior, system, g, H);
            REQUIRE(H.rows() == SystemLocalisation::nx);
            const double h = 1e-6;
            for (int j = 0; j < SystemLocalisation::nx; ++j)
            {
                Eigen::VectorXd xp = xPrior, xm = xPrior;
                xp(j) += h;
                xm(j) -= h;
                Eigen::VectorXd gp, gm;
                meas.logLikelihood(xp, system, gp);
                meas.logLikelihood(xm, system, gm);
                const Eigen::VectorXd col = (gp - gm)/(2*h);
                for (int i = 0; i < SystemLocalisation::nx; ++i)
                {
                    CHECK(H(i, j) == doctest::Approx(col(i)).epsilon(1e-3).scale(1e4));
                }
            }
        }

        THEN("only the body-rate block of the Hessian is populated")
        {
            // The model is exactly independent of the other fifteen states, and
            // the gradient/Hessian overloads exploit that. If a future change
            // makes the likelihood depend on, say, the camera bias, this is the
            // test that has to be revisited along with it.
            Eigen::VectorXd g;
            Eigen::MatrixXd H;
            meas.logLikelihood(xPrior, system, g, H);
            Eigen::MatrixXd rest = H;
            rest.block<3, 3>(SystemLocalisation::iOmega, SystemLocalisation::iOmega).setZero();
            CHECK(rest.norm() == doctest::Approx(0.0));

            Eigen::VectorXd gRest = g;
            gRest.segment<3>(SystemLocalisation::iOmega).setZero();
            CHECK(gRest.norm() == doctest::Approx(0.0));
        }
    }

    GIVEN("A filter whose rate state is wrong and a flow measurement that knows better")
    {
        const FlowFrame ff = makeFlowFrame(omegaTrue, dt, Rbc, Rbc, 200, 0.001);

        const Eigen::Vector3d omegaPrior = omegaTrue + Eigen::Vector3d(0.0, 0.0, 0.20);
        constexpr double priorSigma = 0.3;
        SystemLocalisation system = systemAt(stateWithRate(omegaPrior), priorSigma);

        WHEN("the measurement is applied")
        {
            MeasurementFlowRotation meas(0.0, ff, system);
            REQUIRE(meas.usable());
            system.process(meas);

            // Both checks are against the analytic scalar Gaussian update rather
            // than a loose bound, because the quantity under test is exactly the
            // one the interval term sets. A measurement that omitted it would be
            // ~13x sharper here and would sail past any bound generous enough to
            // pass, which is how the original version of this model got as far as
            // a full run before its overconfidence showed up as a 1.28 m RMSE.
            const double sm = meas.sigma()(2);
            const double K = priorSigma*priorSigma/(priorSigma*priorSigma + sm*sm);

            THEN("the posterior rate moves towards the rate that generated the flow")
            {
                const Eigen::Vector3d omegaPost =
                    system.density.mean().segment<3>(SystemLocalisation::iOmega);
                const double before = (omegaPrior - omegaTrue).norm();
                const double after = (omegaPost - omegaTrue).norm();
                CAPTURE(before);
                CAPTURE(after);
                CAPTURE(sm);
                CHECK(after < before);
                CHECK(after == doctest::Approx((1.0 - K)*before).epsilon(0.05));
            }

            THEN("the posterior rate is sharpened by exactly what the measurement claims")
            {
                const Eigen::Matrix3d P = system.density.cov()
                    .block<3, 3>(SystemLocalisation::iOmega, SystemLocalisation::iOmega);
                const double expected = 1.0/std::sqrt(1.0/(priorSigma*priorSigma) + 1.0/(sm*sm));
                CHECK(std::sqrt(P(2, 2)) < priorSigma);
                CHECK(std::sqrt(P(2, 2)) == doctest::Approx(expected).epsilon(0.05));
            }
        }
    }
}

SCENARIO("MeasurementFlowRotation rejects what it should")
{
    const double dt = 1.0/30.0;
    const Eigen::Vector3d omegaTrue(0.0, 0.0, 0.5);
    const Eigen::Matrix3d Rbc = Eigen::Matrix3d::Identity();

    GIVEN("An invalid flow frame")
    {
        FlowFrame ff = makeFlowFrame(omegaTrue, dt, Rbc, Rbc);
        ff.valid = false;
        SystemLocalisation system = systemAt(stateWithRate(omegaTrue));
        MeasurementFlowRotation meas(0.0, ff, system);

        THEN("it is not usable and contributes nothing")
        {
            CHECK_FALSE(meas.usable());
            CHECK(meas.logLikelihood(stateWithRate(omegaTrue), system) == doctest::Approx(0.0));

            Eigen::VectorXd g;
            Eigen::MatrixXd H;
            meas.logLikelihood(stateWithRate(omegaTrue), system, g, H);
            CHECK(g.norm() == doctest::Approx(0.0));
            CHECK(H.norm() == doctest::Approx(0.0));
        }
    }

    GIVEN("Flow contaminated with matches that do not fit any rigid rotation")
    {
        FlowFrame ff = makeFlowFrame(omegaTrue, dt, Rbc, Rbc, 120, 0.0005);
        // A third of the features belong to something moving through the scene.
        std::mt19937 gen(7);
        std::uniform_real_distribution<double> kick(-0.2, 0.2);
        for (std::size_t j = 0; j < ff.matches.size(); j += 3)
        {
            ff.matches[j].uCurr = (ff.matches[j].uCurr
                                 + Eigen::Vector3d(kick(gen), kick(gen), kick(gen))).normalized();
        }

        SystemLocalisation system = systemAt(stateWithRate(omegaTrue), 0.3);
        MeasurementFlowRotation meas(0.0, ff, system);

        THEN("the pre-gate drops the worst of them")
        {
            CHECK(meas.numGated() > 0);
            REQUIRE(meas.usable());
        }

        THEN("the surviving fit still peaks near the true rate")
        {
            // The robust mixture is what does the work here: the pre-gate is
            // deliberately loose, so outliers do reach the likelihood.
            const Eigen::VectorXd xTrue = stateWithRate(omegaTrue);
            Eigen::VectorXd xOff = xTrue;
            xOff(SystemLocalisation::iOmega + 2) += 0.10;
            CHECK(meas.logLikelihood(xTrue, system) > meas.logLikelihood(xOff, system));
        }
    }
}
